### ISSUE TITLE
Is there a corresponding paper?

### ISSUE THREAD

**Issue by cacacadaxia** [simenandresen/Simulink-Underwater-Robotics-Simulator#1]
This is great work, but it is not easy to understand the various parts of the work. 
Want to know the intention of the authors to provide corresponding papers?

**Comment by cacacadaxia** [comment]
got it

**Comment by CodeWanglufei** [comment]
> 这是一项伟大的工作，但要理解工作的各个部分并不容易。 想知道作者提供相应论文的意图？

Did you find the papers?
